### ISSUE TITLE
Error reading fused file

### ISSUE THREAD

**Issue by APOS80** [openphotogrammetry/meshroomcl#11]
Got an error, see text file.

[error.txt](https://github.com/openphotogrammetry/meshroomcl/files/7062579/error.txt)

**Comment by APOS80** [comment]
Here's fused.ply and also the log file.

[files.zip](https://github.com/openphotogrammetry/meshroomcl/files/7070255/files.zip)

**Comment by revisionarian** [comment]
Hi @APOS80, thanks a lot for posting your fused.ply file. We have been able to reproduce the error that you reported, and we will have a bug fix in the next release of MeshroomCL.

In the meantime, you can avoid this error by simply making sure that the "Compute Visibility" attribute of the MultiviewStereoCL node is disabled (this is the default setting). You do not need this attribute enabled to utilize the photogrammetry pipeline, and if you want access to your project's reconstructed 3D point cloud rather than the 3D mesh, then you can find it as the file `MeshroomCache\MultiviewStereoCL\*\fused.ply`.

**Comment by revisionarian** [comment]
The latest release (MeshroomCL 0.7.1) fixes this problem.
