### ISSUE TITLE
MultiviewStereoCL fails with StructureFromMotion

### ISSUE THREAD

**Issue by wilecoyote2015** [openphotogrammetry/meshroomcl#20]
I have constructed a Pipeline using the native StructureFromMotion (non-CL) connected to MultiviewStereoCL.
The motivation is that the StructureFromMotionCL node did not perfom well on feature extraction and matching for my dataset, so that I need the options from the native FeatureExtraction and FeatureMatching nodes.

However, the MultiViewStereoCL node fails with the following error:
```
ERROR:root:Error on node computation: Error on node "MultiviewStereoCL_1":
Log:
[option_manager.cc:761] Check failed: ExistsDir(*image_path)
ERROR: Invalid options provided.
```

The Graph file is attached.
[mg_bug.zip](https://github.com/openphotogrammetry/meshroomcl/files/7576057/mg_bug.zip)

**Comment by revisionarian** [comment]
Thanks for reporting this bug, @wilecoyote2015. We have been able to replicate the same problem, and will see if we can provide a fix for this.

We are also very interested in the nature of your image dataset, which performs better with the Meshroom SfM nodes than with MeshroomCL's StructureFromMotionCL node. Is there any chance that we could get access to your images (or a subset of them) in order for us to study where MeshroomCL SfM is falling short?

**Comment by revisionarian** [comment]
Hi @wilecoyote2015, the bug that you reported has been fixed in the latest release of MeshroomCL (version 0.8.0). We added an option under the  _File &rarr; New Pipeline_ menu that will instantiate a photogrammetry pipeline with the original Meshroom (non-CL) StructureFromMotion node connected to the MultiviewStereoCL node. 

Thanks for your interest, and let us know if you have any more problems!
